server:
    port: 8761

eureka:
    server:
        enable-self-preservation: false #关闭自我保护
        eviction-interval-timer-in-ms: 4000 #清理间隔（单位毫秒，默认是60*1000）
    instance:
        hostname: localhost
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: eurka-server
